name: Azure Static Web Apps CI/CD - Dev

on:
  push:
    branches:
      - Dev  # Case-sensitive branch name
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - Dev

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy to Dev
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      
      
      - name: Install OIDC Client
        if: false  # Disabled by default (remove if needed)
        run: npm install @actions/core@1.6.0 @actions/http-client
      
      - name: Get Id Token
        if: false  # Disabled by default (remove if needed)
        uses: actions/github-script@v6
        id: idtoken
        with:
          script: |
            const coredemo = require('@actions/core')
            return await coredemo.getIDToken()
          result-encoding: string

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_NICE_CLIFF-0C051CF10 }}
          action: "upload"
          app_location: "/" 
          api_location: "" 
          output_location: "dist"
          # Only pass token if OIDC is enabled:
          github_id_token: ${{ steps.idtoken.outputs.result }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Cleanup PR Preview
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
